Update 1.11.0-missing-stdint.patch
src/weston-launch.c:36:19: fatal error: error.h: No such file or directory
#include <error.h>
                   ^
compilation terminated.